#!/bin/bash
clear

log()
{
      echo "$(date) $@"
}

export publicKeyFile=alice.gpg
export destination=alice@example.com
export thisScript=$(basename ${0})
export tempFile=$(mktemp /tmp/${thisScript}.XXXXXX)

#################################################################################
#
# This script is not entirely useful in relation to other examples in this suite.
#   It assumes that you have a keystore and exports the public key only.
#
# It's purpose is the generate a public key to emulate the fact that you have a
# public key from the recipient in subsequent scripts in this suite of examples.
#
# Before running this script.  Manully execute:
#    gpg --full-generate-key
#
# Note also, the private key generated by running gpg --full-generate-key is also
# used in a subsequent example decrypt script.
#################################################################################

log "[INFO] Listing gpg keys on this system" 
gpg --list-keys

log "[INFO] Exporting public key ${destination} to ${publicKeyFile}" 
log "[INFO] tempfile : ${tempFile}"
gpg --output ${publicKeyFile} --export ${destination} >> ${tempFile} 2>&1
cat ${tempFile}
retVal=$?
if [ ${retVal} -ne 0 ]; then
   log "[ERROR] exporting public key for ${destination} to ${publicKeyFile}"
   exit 8
fi
if [ ! -f ${publicKeyFile} ]; then
    log "[ERROR] unable to locate exported key file ${publicKeyFile}"
    exit 8
fi

log "[INFO] Removing tempfile: ${tempFile}" 
rm ${tempFile}

log "[INFO] Exporting public key ${destination} to ${publicKeyFile} - Done"


#################################################################################
# WSL useful commands
# "/mnt/c/Program Files/IDM Computer Solutions/UltraEdit/uedit64.exe" 1_alice_generate_keys.sh
# sudo chown jarrod *.sh; chmod 755 *.sh; ./1_alice_generate_keys.sh

#################################################################################
# Other useful commands for reference
#gpg --full-generate-key
#gpg --import bob.gpg
#gpg --edit-key bob@example.com

#gpg --list-keys
#gpg --delete-secret-keys 44BB12DFC8D005843C8C7456A6F577A90134C128
#gpg --delete-keys 44BB12DFC8D005843C8C7456A6F577A90134C128